name: "Terraform Management Pipeline"

on:
  workflow_dispatch:
  push:
    branches: [main]
    # paths:
    #   - 'management-tf/**'

env:
  TF_VAR_client_secret: ${{ vars.AZURE_CLIENT_SECRET }}    

jobs:
  deploy:
    runs-on: ubuntu-latest        
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform fmt
      - run: terraform apply -auto-approve